#!/bin/bash

echo "Enter the 1st value:"
read val1

echo "Enter the 2nd value:"
read val2

val=`expr $val1 + $val2`
echo "sum of 2 numbers is: $val"

val=`expr $val1 \* $val2`
echo "multiplication of 2 numbers is: $val"

val=`expr $val1 - $val2`
echo "substraction of 2nd from 1st gives you: $val"

val=`expr $val1 % $val2`
echo "modulus of 2 numbers is: $val"

